# default
spring:
  profiles:
    default: local
    active: ${env}
server:
  servlet:
    context-path: /v1/api
  port: 8080



############ local ###########
---
spring:
  config:
    activate:
      on-profile: local

  test:
    text: local working

  datasource:
    url: jdbc:h2:mem:pickLocal  # h2 in memory
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:        # http://127.0.0.1:8080/v1/api/h2-console
    console: # H2 DB
      enabled: true           # H2 Console
      path: /h2-console       # H2 Console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # data.sql ??


springdoc:  # https://springdoc.org/#properties 문서 참고
  packages-to-scan: com.toy.pick.api.controller # 해당 경로 풀스캔
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: / # http://localhost:8080/v1/api/swagger-ui/index.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

############ dev ###########
---
spring:
  config:
    activate:
      on-profile: dev

#  mysql:
#    datasource:
#      jdbcUrl: jdbc:log4jdbc:mysql://${rds.hostname}:${rds.port}/pick?autoReconnect=true&socketTimeout=60000&connectTimeout=60000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8&useSSL=false
#      username: ${rds.username}
#      password: ${rds.password}
#      connection-init-sql: SET NAMES utf8mb4
  test:
    text: dev working

  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/pick
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never # data.sql ?? ??

springdoc:  # https://springdoc.org/#properties 문서 참고
  packages-to-scan: com.toy.pick.api.controller # 해당 경로 풀스캔
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: / # http://localhost:8080/v1/api/swagger-ui/index.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

############ test ###########
---
spring:
  config:
    activate:
      on-profile: test


#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/...
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#  jpa:
#    show-sql: true
